export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const FILTER_CLOTHING = "FILTER_CLOTHING";
export const FILTER_ACCESSORIES = "FILTER_ACCESSORIES";
export const FILTER_BEAUTY = "FILTER_BEAUTY";
export const FILTER_HOUSEHOLD = "FILTER_HOUSEHOLD";

export const FILTER_TYPE = "FILTER_TYPE";
export const FILTER_DISCOUNT = "FILTER_DISCOUNT";